version: "3.7"
services:
  db:
    image: mariadb:latest
    volumes:
    - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  php:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
        - .:/var/www:cached
        - ./docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:cached
    depends_on:
      - db
  web:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./logs/nginx:/var/log/nginx:delegated
    depends_on:
      - php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
    - 8025:8025
volumes:
  db-data: